version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: adonis_backend
    ports:
      - "3333:3333"
    volumes:
      - ./be:/app
    environment:
      - NODE_ENV=development
      
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
