import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import { ReactQueryClientProvider } from '@/components/ReactQueryClientProvider'
import { Navbar } from '@/components/navbar/Navbar'
import { ThemeProvider } from '@/components/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang='en'>
        {/* <body className={`${roboto.className} dark:bg-[#202020]`}> */}
        <body className={roboto.className}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <div>
              <Navbar />
              {/* <div className='container max-w-[1024px]'>{children}</div> */}
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}
